In [2]:
import torch
import torch.nn as nn

In [3]:
x = torch.tensor([1.0, 2.0, 3.0])
y = x * 2

print(x, y)

tensor([1., 2., 3.]) tensor([2., 4., 6.])


In [4]:
x = torch.tensor(3.0, requires_grad=True) # requires_grad track ops on x
y = x ** 2 # autograd records op
y.backward() # computes dy/dx => 2x, where x = 3 ==> 2x3 = 6

print(x.grad) # should be 6, a tensor


tensor(6.)


In [5]:
model = nn.Linear(4, 1)
x = torch.randn(10, 4)
y = model(x)

print(model)
print(x)
print(y)

Linear(in_features=4, out_features=1, bias=True)
tensor([[ 0.6093,  0.8659,  0.4209, -0.3611],
        [ 1.2583,  1.9511,  0.0357,  0.7035],
        [ 0.3391,  0.3302, -0.0308,  0.8942],
        [ 0.3466, -0.1806,  0.5480, -0.9681],
        [-0.8438, -1.3754, -1.4003,  1.5483],
        [-0.0828, -0.2265, -0.6673, -0.6184],
        [-0.0254,  0.8480,  0.4257, -2.2745],
        [-0.3410,  0.8254,  0.3138,  2.2194],
        [ 0.8622, -2.0978, -0.3498,  0.8885],
        [ 0.6243,  1.3851,  0.3209, -0.6111]])
tensor([[ 0.6089],
        [ 0.9189],
        [-0.0563],
        [ 0.2359],
        [-1.7823],
        [-0.4858],
        [ 0.6964],
        [-0.0376],
        [-1.0981],
        [ 0.8211]], grad_fn=<AddmmBackward0>)


In [6]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(4, 8)
        self.fc2 = nn.Linear(8, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

model = MyModel()
print(model)

MyModel(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=1, bias=True)
)
